# 修改端口
server:
  port: 80

# 数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_web
    username: root
    password: root123

# 开启下划线命名与驼峰命名自动转换
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true